Labixa/Labixa/Controllers/ProductHomeController.cs
using Labixa.Models;
using Outsourcing.Data.Models;
using Outsourcing.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PagedList;
using Outsourcing.Core.Extensions;
namespace Labixa.Controllers
{
    public class ProductHomeController : BaseHomeController
    {  private readonly IProductService _productService;
        private readonly IVendorService _vendorService;
        private readonly IBlogService _blogService;
        private readonly IBlogCategoryService _blogCategoryService;
        private readonly IWebsiteAttributeService _websiteAttributeService;
        private readonly IStaffService _staffService;
        private readonly IOrderService _orderService;
        private readonly ITypeNotifyService _typeNotifyService;
        private readonly IProductAttributeMappingService _productAttributeMappingService;
        private readonly IProductCategoryMappingService _productCategoryMappingService;
        private readonly IProductCategoryService _productCategory;


        public ProductHomeController(IProductService productService, IBlogService blogService,
            IWebsiteAttributeService websiteAttributeService, IBlogCategoryService blogCategoryService,
            IStaffService staffService, IProductAttributeMappingService productAttributeMappingService, IVendorService _vendorService
           , IOrderService _orderService, ITypeNotifyService _typeNotifyService,
            IProductCategoryMappingService _productCategoryMappingService, IProductCategoryService _productCategory)
        {
            this._productService = productService;
            this._blogService = blogService;
            this._websiteAttributeService = websiteAttributeService;
            this._blogCategoryService = blogCategoryService;
            this._vendorService = _vendorService;
            this._staffService = staffService;
            this._productAttributeMappingService = productAttributeMappingService;
            this._orderService = _orderService;
            this._typeNotifyService = _typeNotifyService;
            this._productCategoryMappingService = _productCategoryMappingService;
            this._productCategory = _productCategory;
        }

        
        public ActionResult SanPham(string slug)
        {

            var item = _productAttributeMappingService.GetProductAttributeMappings();
            ProductDetailsModel model = new ProductDetailsModel();
            model.product = _productService.GetProductBySlug(slug);
            double productPrice = model.product.OrginalPrice;
            try
            {
                if (model.product.ProductAttributeMappings.Where(p => p.ProductAttributeId == 24).FirstOrDefault().Value.Equals("true"))
                {
                    model.listRelated = _productAttributeMappingService.GetProductAttributeMappings().Where(p => p.Value.Equals("true") && p.ProductAttributeId == 24).Select(p => p.Product).Where(e => (e.OrginalPrice >= productPrice - 1000000000) && (e.OrginalPrice <= productPrice + 1000000000)).Take(6).ToList();
                }
                else
                {
                    model.listRelated = _productAttributeMappingService.GetProductAttributeMappings().Where(p => !p.Value.Equals("true") && p.ProductAttributeId == 24).Select(p => p.Product).Where(e => (e.OrginalPrice >= productPrice - 2000000) && (e.OrginalPrice <= productPrice + 2000000)).Take(6).ToList();
                }
            }
            catch
            {
                model.listRelated = null;
            }
            
            
            //if (model.li)
            //{

            //}
            var moigioi = GetInfo(model.product.ProductAttributeMappings.Where(p => p.ProductAttributeId == 19).FirstOrDefault().Value);
            model.user = moigioi;
            model.products = _productService.GetAllProducts().ToList();
            return View("SanPham", model);
        }
        public ActionResult Search()
        {
            SearchModelView search = new SearchModelView();
            SelectListItem list = new SelectListItem();
            list.Value = "Địa điểm";
            list.Text = "Địa điểm";
            List<SelectListItem> listCate = new List<SelectListItem>();
            listCate.Add(list);
            listCate.AddRange(_productCategory.GetProductCategories().ToSelectListItems(-1, 1));
            ViewBag.categoryList = listCate;
            return PartialView("Search", search);
        }

        public ActionResult ChoBanQuan(string slug, int? page = 1)
        {
            int pageSize = 12;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            ViewBag.slug = slug;

            ViewBag.category = _productCategory.GetProductCategories();

           
            //ProductViewModel model = new ProductViewModel();

            int categoryId = _productCategory.GetProductCategories().Where(q => q.Slug.Equals(slug)).Select(k => k.Id).FirstOrDefault();
            var model = _productAttributeMappingService.GetProductAttributeMappings().Where(p => p.Value.Equals("true") && p.ProductAttributeId == 24 && p.Product.OldPrice == categoryId && p.Product.IsPublic).Select(p => p.Product).OrderByDescending(p => p.Id).ToPagedList(pageIndex, pageSize);
            //model.products = _productCategoryMappingService.GetProductCategoryMappings().Where(p => p.ProductCategoryId == categoryId).ToPagedList(pageIndex, pageSize);

            return View("ChoBanQuan", model);
        }
        
        public ActionResult ChoThueQuan(string slug, int? page = 1)
        {
            int pageSize = 12;
            int pageIndex = 1;
            pageIndex = page.HasValue ? Convert.ToInt32(page) : 1;
            ViewBag.slug = slug;
            //ProductViewModel model = new ProductViewModel();
            int categoryId = _productCategory.GetProductCategories().Where(q => q.Slug.Equals(slug)).Select(k => k.Id).FirstOrDefault();
            var model = _productAttributeMappingService.GetProductAttributeMappings().Where(p => p.Value.Equals("false") && p.ProductAttributeId == 24 && p.Product.OldPrice == categoryId && p.Product.IsPublic).Select(p => p.Product).OrderByDescending(p => p.Id).ToPagedList(pageIndex, pageSize);
            return View("ChoThueQuan", model);
        }
        
        public ActionResult popularProduct()
        {
            //var list = _blogService.GetBlogs().OrderByDescending(p => p.DateCreated).Take(4);
            
            var list = _productAttributeMappingService.GetProductAttributeMappings().Where(p => p.ProductAttributeId == 28).OrderByDescending(d => d.Value).Take(3);
            
            return PartialView("_popularProduct", list);
        }


        [HttpPost]
        [ValidateInput(false)]
        public ActionResult ContactNow( string UserName,string Id, string name, string phone, string email, string message, string slug)
        {
            if (ModelState.IsValid)
            {
                Vendor vendor = new Vendor();
                vendor.Content = UserName;
                vendor.Note = Id;
                vendor.Name = name;
                vendor.Phone = phone;
                vendor.Address = email;
                vendor.Description = message;
                vendor.Type = "1";
                //Mapping to domain
                //Create Blog
                _vendorService.CreateVendor(vendor);
                Console.WriteLine("ok");
                return Redirect("/san-pham/" + slug);
                //chua thong bao gui tin nhan thanh cong
                
            }
            else
            {
                //return RedirectToAction("SanPham", "ProductHome");
                return Redirect("/san-pham/" + slug);
            }
        }
	}
}

Labixa/Labixa/Views/ProductHome/ChoThueQuan.cshtml
@{
    ViewBag.url = "www.humiland.com";
    ViewBag.title = "Humiland Trang Giao Dịch Bất Động Sản Tại TP HCM";
    ViewBag.description = "CHUYÊN MUA BÁN NHÀ PHỐ, ĐẤT NỀN TP HCM";
    ViewBag.image = "/Content/humiland/images/logo2.png";
    Layout = "~/Views/Shared/_HumilandLayout.cshtml";
}
@using PagedList.Mvc;
@using Outsourcing.Core.Common;
@using PagedList;
@model IPagedList<Outsourcing.Data.Models.Product>
<style>
    input[type='range'] {
        width:180px;
    }
    .rangeslider .right {
        margin-right:20px;
    }
</style>
<div class="page-title page-main-section">
    <div class="container padding-bottom-top-120 text-uppercase text-center">
        <div class="main-title">
            <h1>Nhà đất</h1>
            <div class="line_4"></div>
            <div class="line_5"></div>
            <div class="line_6"></div>
            @*<a href="/">Trang chủ</a>
                    <span><i class="fa fa-angle-double-right" aria-hidden="true"></i></span>
                <a href="@Url.Action("SanPham", "ProductHome")">Nhà Bán</a>*@
        </div>
    </div>
</div>
<!--PAGE TITLE -->

<section id="agent-p-2" class="listing-1 bg_light padding_top">
    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <h2 class="uppercase"><span class="color_red">DỰ ÁN </span>NHÀ ĐẤT</h2>
                <div class="line_1"></div>
                <div class="line_2"></div>
                <div class="line_3"></div>
            </div>
        </div>
        <div class="row">
            <div class="col-md-8 col-sm-12 col-xs-12">
                <form class="findus">
                    <div class="row">
                        @foreach (var item in Model)
                        {
                            try
                            {
                                if (!item.Deleted)
                                {

                                    <div class="col-md-12 col-sm-12">
                                        <div class="property_item heading_space row">
                                            <div class="image col-md-3 col-sm-3 col-xs-4">
                                                @try
                                                {
                                                    <img src="@item.ProductPictureMappings.FirstOrDefault().Picture.Url" alt="listin" class="img-responsive">
                                                }
                                                catch (Exception)
                                                {

                                                    <img src="" alt="listin" class="img-responsive">
                                                }
                                               
                                                <div class="overlay">
                                                    <div class="centered">
                                                        <a class="link_arrow white_border" href="/san-pham/@item.Slug">
                                                            Thông tin chi tiết
                                                        </a>
                                                    </div>
                                                </div>
                                                <div class="feature">
                                                    <span class="tag">
                                                        Nổi bật
                                                    </span>
                                                </div>
                                                <div class="price">
                                                    <span class="tag">
                                                        @if (item.ProductAttributeMappings.Where(p => p.ProductAttributeId == 24).FirstOrDefault().Value.Equals("true"))
                                                        {
                                                            <span>
                                                                Cần bán
                                                            </span>
                                                        }
                                                        else
                                                        {
                                                            <span>
                                                                Cần cho thuê
                                                            </span>
                                                        }
                                                    </span>
                                                </div>
                                                <div class="property_meta">
                                                    <span>
                                                        <i class="fa fa-object-group"></i>
                                                        @item.ProductAttributeMappings.Where(p => p.ProductAttributeId == 3).FirstOrDefault().Value @item.ProductAttributeMappings.Where(p => p.ProductAttributeId == 3).FirstOrDefault().ProductAttribute.Name
                                                    </span>
                                                    <span>
                                                        <i class="fa fa-bed"></i>
                                                        @item.ProductAttributeMappings.Where(p => p.ProductAttributeId == 4).FirstOrDefault().Value Phòng ngủ
                                                    </span>
                                                    <span>
                                                        <i class="fa fa-bath"></i>
                                                        @item.ProductAttributeMappings.Where(p => p.ProductAttributeId == 5).FirstOrDefault().Value Phòng tắm
                                                    </span>
                                                    <span>
                                                        <i class="fa fa-car"></i>
                                                        @{
                                                            if (item.ProductAttributeMappings.Where(p => p.ProductAttributeId == 7).FirstOrDefault().Value.Equals(true))
                                                            {
                                                                <span>
                                                                    Có
                                                                </span>
                                                            }
                                                            else
                                                            {
                                                                <span>
                                                                    Không
                                                                </span>
                                                            }
                                                        }Nhà xe
                                                    </span>
                                                </div>
                                            </div>
                                            <div class="proerty_content col-md-9 col-sm-9 col-xs-8">
                                                <div class="proerty_text">
                                                    <h6>
                                                        <strong>
                                                            <a href="/san-pham/@item.Slug">
                                                                @*@slitString.TruncateAtWord(@item.Name, 20)*@
                                                                @item.Name
                                                            </a>
                                                        </strong>
                                                    </h6>
                                                    @*<span class="bottom10">
                                                        @item.ProductAttributeMappings.Where(p => p.ProductAttributeId == 18).FirstOrDefault().Value
                                                    </span>*@
                                                    <p>
                                                        <strong>
                                                            @item.OrginalPrice.ToString("#,##0") VND
                                                        </strong>
                                                    </p>
                                                </div>
                                                <div class="favroute clearfix">
                                                    <p class="pull-left">
                                                        <i class="icon-calendar2"></i>
                                                        @item.DateCreated.ToLongDateString()
                                                    </p>

                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                                                    }
                                                                }
                                                                catch (Exception)
                                                                {

                                                                    continue;
                                                                }

                                                            }
                    </div>
                    <ul class="pager top40 padding_bottom">
                        @*<li><a href="#.">1</a></li>
                            <li class="active"><a href="#.">2</a></li>
                            <li><a href="#.">3</a></li>*@

                        @Html.PagedListPager(Model, page => Url.Action("ChoThueQuan", "ProductHome", new { page, slug = (string)ViewBag.slug }))
                    </ul>
                </form>
            </div>
            <div class="col-md-4 colsm-4 col-xs-12">
                <div class="property-query-area padding-all20">
                    <div class="row">
                        <div class="col-md-12">
                            <h3 class="text-uppercase  bottom40 top10">Tìm kiếm <span class="color_red">Nâng cao</span></h3>
                        </div>
                    </div>
					 @Html.Action("Search", "ProductHome")
                </div>
            </div>
        </div>
    </div>

</section>
<!-- LISTING -->

Labixa/Labixa/Views/ProductHome/Search.cshtml
@using PagedList.Mvc;
@using Outsourcing.Core.Common;
@using PagedList;
@using Outsourcing.Data.Models;
@model Labixa.Models.SearchModelView

<form class="findus" action="/tim-kiem" method="get">
    <div class="row">
        <div class="col-md-12">
            <div class="single-query">
                <input class="keyword-input" placeholder="Từ khóa " type="text" name="keyword">
            </div>
        </div>
        <div class="col-md-12">
            <div class="single-query">
                <div class="intro">
                    @*<select name="place">
                            <option>Địa điểm</option>
                            @foreach (var item in ViewBag.category)
                            {
                                <option value="@item.Name">@item.Name</option>
                            }
                        </select>*@
                    @Html.DropDownListFor(model => model.place, (IEnumerable<SelectListItem>)ViewBag.categoryList)
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="single-query">
                <div class="intro">
                    <select name="type">
                        <option>Loại nhà đất</option>
                        <option value="true">Cho bán</option>
                        <option value="false">Cho thuê</option>
                    </select>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="single-query">
                <div class="intro">
                    <select name="direction">
                        <option>Hướng nhà</option>
                        <option value="Đông">Đông</option>
                        <option value="Tây">Tây</option>
                        <option value="Nam">Nam</option>
                        <option value="Bắc">Bắc</option>
                        <option value="Đông Bắc">Đông Bắc</option>
                        <option value="Tây Bắc">Tây Bắc</option>
                        <option value="Tây Nam">Tây Nam</option>
                        <option value="Đông Nam">Đông Nam</option>
                    </select>
                </div>
            </div>
        </div>

    </div>
    <div class="row search-2">
        <div class="col-md-12">
            <div class="row">
                <div class="col-md-6 col-sm-6">
                    <div class="single-query">
                        <input class="keyword-input" placeholder="Diện tích nhỏ nhất" type="text" name="minArea">
                    </div>
                </div>
                <div class="col-md-6 col-sm-6">
                    <div class="single-query">
                        <input type="text" class="keyword-input" placeholder="Diện tích lớn nhất" name="maxArea">
                    </div>
                </div>
            </div>
        </div>
        <div class="col-md-12">
            <div class="single-query-slider">
                <label>Mức giá:</label>

                <div class="rangeslider">
                    <input class="min" name="minPrice" type="range" min="0" max="50" value="0" />
                    <input class="max" name="maxPrice" type="range" min="0" max="50" value="50" />
                    <span class="range_min light left">Từ 0 tỉ VND</span>
                    <span class="range_max light right">Đến 50 tỉ VND</span>
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-6">
            <div class="query-submit-button top30">
                <button type="submit" class="btn_fill">Tìm kiếm</button>
            </div>
        </div>
    </div>
</form>

<script>
    (function () {
        function addSeperator(nStr) {
            nStr += '';
            var x = nStr.split('.');
            var x1 = x[0];
            var x2 = x.length > 1 ? '.' + x[1] : '';
            var rgx = /(\d+)(\d{3})/;
            while (rgx.test(x1)) {
                x1 = x1.replace(rgx, '$1' + '.' + '$2');
            }
            return x1 + x2;
        }

        function rangeInputChangeEventHandler(e) {
            var rangeGroup = $(this).attr('name'),
                minBtn = $(this).parent().children('.min'),
                maxBtn = $(this).parent().children('.max'),
                range_min = $(this).parent().children('.range_min'),
                range_max = $(this).parent().children('.range_max'),
                minVal = parseInt($(minBtn).val()),
                maxVal = parseInt($(maxBtn).val()),
                origin = $(this).context.className;

            if (origin === 'min' && minVal > maxVal - 1) {
                $(minBtn).val(maxVal - 1);
            }
            var minVal = parseInt($(minBtn).val());
            $(range_min).html('Từ ' + addSeperator(minVal * 1) + ' tỉ VND');


            if (origin === 'max' && maxVal - 1 < minVal) {
                $(maxBtn).val(1 + minVal);
            }
            var maxVal = parseInt($(maxBtn).val());
            $(range_max).html('Đến ' + addSeperator(maxVal * 1) + ' tỉ VND');
        }

        $('input[type="range"]').on('input', rangeInputChangeEventHandler);
    })();
</script>

Labixa/Labixa/Views/ProductHome/_popularProduct.cshtml
@model IEnumerable<Outsourcing.Data.Models.ProductAttributeMapping>
@if (Model.Any() && Model != null)
{
    foreach (var item in Model.Where(p=>!p.Product.Deleted))
    {

        <div class="item">
            <div class="property_item heading_space">
                <div class="image">
                    
                    <a href="@item.Product.Slug"><img src="@item.Product.ProductPictureMappings.FirstOrDefault().Picture.Url" alt="listin" class="img-responsive"></a>
                    <div class="feature"><span class="tag-2"> @if (item.Product.ProductAttributeMappings.Where(p => p.ProductAttributeId == 24).FirstOrDefault().Value.Equals("true"))
                    {<span>Cần bán</span> }
                    else
                    {<span>Cần cho thuê</span>}</span></div>
                
                </div>
            </div>
        </div>
    }

}